version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: py_job_portal_postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./src/.env
volumes:
  progresDB: